version: 2
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout

      - setup_remote_docker

      # build and push Docker image
      - run: |
          TAG=fpm
          docker build -t shyd/php-test:$TAG -f Dockerfile.$TAG .
          TAG=7-fpm
          docker build -t shyd/php-test:$TAG -f Dockerfile.$TAG .
          TAG=5-fpm
          docker build -t shyd/php-test:$TAG -f Dockerfile.$TAG .
          
      - deploy:
        release:
          tag: /deploy-.*/
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push shyd/php-test:fpm
            docker push shyd/php-test:7-fpm
            docker push shyd/php-test:5-fpm